FROM node:18.16.1-slim

WORKDIR /opt/bifrost

# install dependencies
COPY bifrost-zero-common/ bifrost-zero-common/
COPY bifrost-zero-sdk/ bifrost-zero-sdk/

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

# copy module
COPY bifrost-zero-modules/package*.json bifrost-zero-modules/
COPY bifrost-zero-modules/ModuleTemplate/ bifrost-zero-modules/ModuleTemplate/
RUN cd /opt/bifrost/bifrost-zero-sdk/ && npm install
RUN cd /opt/bifrost/bifrost-zero-modules/ && npm install
RUN cd /opt/bifrost/bifrost-zero-modules/ModuleTemplate && npm install

WORKDIR /opt/bifrost/bifrost-zero-modules/

EXPOSE 1809
CMD ["npm", "run", "ModuleTemplate"]