FROM node:18.16.1-slim

WORKDIR /opt/energy-community-pv-simulator/

# set up node environment
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

# copy module files
COPY src/ ./src/
COPY data/ ./data/
COPY energy-community-pv-simulator.ts ./energy-community-pv-simulator.ts

RUN npm run tsc

CMD ["npm", "run", "module"]