FROM node:18.16.1-slim

WORKDIR /opt/siemergy-analysis-module/

# set up node environment
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

# copy module files
COPY src/ ./src/
COPY data/ ./data/
COPY siemergy-analysis-module.ts ./siemergy-analysis-module.ts

RUN npm run tsc

CMD ["npm", "run", "module"]